"""
patch_ml_template.py
Updates the STREAMLIT_APP_ML template in base_streamlit.py to match the high-contrast UI.
Also directly updates workspace/current_app/app.py to apply it immediately.
"""
import pathlib

TARGET = pathlib.Path(__file__).resolve().parent / "generator" / "base_streamlit.py"
APP = pathlib.Path(__file__).resolve().parent / "workspace" / "current_app" / "app.py"

INNER = r'''"""
Predictive ML Streamlit app generated by RAD-ML.
Calls a SageMaker endpoint for real-time predictions with a clean dark UI.
"""
from __future__ import annotations

import io
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import streamlit as st
import yaml

try:
    import boto3
except Exception:
    boto3 = None

try:
    import pandas as pd
except Exception:
    pd = None

ROOT = next(
    (parent for parent in Path(__file__).resolve().parents if (parent / "config.yaml").exists()),
    Path(__file__).resolve().parent,
)
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

_cfg_path = ROOT / "config.yaml"
CFG = {}
if _cfg_path.exists():
    try:
        with open(_cfg_path, encoding="utf-8") as f:
            CFG = yaml.safe_load(f) or {}
    except Exception:
        CFG = {}
os.environ.setdefault("AWS_EC2_METADATA_DISABLED", "true")

# ── Page config & high-contrast theme ─────────────────────────────────────────
st.set_page_config(
    page_title="RAD-ML Predictor",
    page_icon="🔮",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
  html, body, [class*="css"] { font-family: 'Inter', sans-serif; }

  /* ── App background ── */
  [data-testid="stAppViewContainer"] {
    background: linear-gradient(160deg, #0b0e1a 0%, #111827 100%);
  }

  /* ── Sidebar overhaul ── */
  [data-testid="stSidebar"] {
    background: linear-gradient(180deg, #1a2035 0%, #0f1629 100%) !important;
    border-right: 2px solid #3b82f6 !important;
  }
  /* All sidebar text bright white */
  [data-testid="stSidebar"] * { color: #f1f5f9 !important; }
  [data-testid="stSidebar"] .stCaption,
  [data-testid="stSidebar"] .stMarkdown p { color: #cbd5e1 !important; font-size: 0.92rem !important; }
  [data-testid="stSidebar"] h1, [data-testid="stSidebar"] h2, [data-testid="stSidebar"] h3 {
    color: #ffffff !important; font-weight: 700 !important;
  }
  /* Sidebar info boxes */
  [data-testid="stSidebar"] .element-container .stAlert {
    background: rgba(59,130,246,0.15) !important;
    border: 1px solid rgba(59,130,246,0.4) !important;
    border-radius: 10px;
  }

  /* ── Main area headings ── */
  h1 { color: #ffffff !important; font-weight: 800 !important; font-size: 2.2rem !important; }
  h2 { color: #e2e8f0 !important; font-weight: 700 !important; }
  h3 { color: #e2e8f0 !important; font-weight: 600 !important; }
  p, .stMarkdown p { color: #cbd5e1 !important; }
  .stCaption { color: #94a3b8 !important; font-size: 0.9rem !important; }

  /* ── Form container ── */
  div[data-testid="stForm"] {
    background: rgba(59,130,246,0.06) !important;
    border: 1px solid rgba(59,130,246,0.3) !important;
    border-radius: 16px;
    padding: 1.5rem 1.8rem;
  }
  [data-testid="stForm"] label {
    color: #e2e8f0 !important; font-weight: 600 !important; font-size: 0.95rem !important;
  }
  .stTextInput > div > div > input {
    color: #ffffff !important;
    background-color: #1e2a42 !important;
    border: 1.5px solid #3b82f6 !important;
    border-radius: 10px !important;
  }

  /* ── Primary button ── */
  .stButton > button[kind="primary"],
  .stFormSubmitButton > button[kind="primary"] {
    background: linear-gradient(135deg, #3b82f6, #8b5cf6) !important;
    color: #ffffff !important;
    font-weight: 700 !important;
    font-size: 1rem !important;
    border: none !important;
    border-radius: 10px !important;
    padding: 0.65rem 1.5rem !important;
    box-shadow: 0 4px 20px rgba(59,130,246,0.4) !important;
    transition: transform 0.15s, box-shadow 0.15s;
  }
  .stButton > button[kind="primary"]:hover,
  .stFormSubmitButton > button[kind="primary"]:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 28px rgba(59,130,246,0.55) !important;
  }

  /* ── Prediction Result ── */
  .prediction-result {
    background: linear-gradient(135deg, rgba(62,207,255,0.12), rgba(124,106,247,0.12));
    border: 1px solid rgba(62,207,255,0.4);
    border-radius: 16px;
    padding: 2.5rem;
    text-align: center;
    margin: 1.5rem 0;
    box-shadow: 0 8px 32px rgba(0,0,0,0.25);
  }

  hr { border-color: rgba(59,130,246,0.2) !important; }
  [data-testid="stSpinner"] p { color: #93c5fd !important; font-weight: 500; }

  /* Upload box */
  [data-testid="stFileUploader"] {
    background: rgba(255,255,255,0.05);
    border: 1px dashed rgba(59,130,246,0.5);
    border-radius: 14px;
    padding: 1rem;
  }
</style>
""", unsafe_allow_html=True)

# ── Config ────────────────────────────────────────────────────────────────────
ENDPOINT_NAME = os.environ.get(
    "SAGEMAKER_ENDPOINT",
    CFG.get("aws", {}).get("sagemaker_endpoint_name", "rad-ml-endpoint"),
)
AWS_REGION = CFG.get("aws", {}).get("region", "us-east-1")
REMOTE_INFERENCE_ENABLED = os.environ.get("SAGEMAKER_REMOTE_ENABLED", "1") == "1"
MOCK_MODE = os.environ.get("RADML_MOCK_MODE", "0") == "1" or not REMOTE_INFERENCE_ENABLED
FEATURES: List[str] = list(CFG.get("ml_features", [])) or [
    "region",
    "area",
    "bedrooms",
    "bathrooms",
    "age_of_property",
]
FEATURE_LABELS = {
    "medinc": "Median Income",
    "houseage": "House Age",
    "averooms": "Average Rooms",
    "avebedrms": "Bedrooms",
    "aveoccup": "Average Occupancy",
    "population": "Population Size",
    "latitude": "Location Latitude",
    "longitude": "Location Longitude",
}

def get_sm_runtime():
    """Create the SageMaker runtime client lazily to avoid startup stalls."""
    if not boto3 or not REMOTE_INFERENCE_ENABLED:
        return None
    try:
        return boto3.client("sagemaker-runtime", region_name=AWS_REGION)
    except Exception:
        return None

# ── Core logic (kept pure for unit-testability) ───────────────────────────────
def _encode_feature(feature_name: str, value: str) -> str:
    """Strip units/symbols and encode a single feature value as a numeric string."""
    value = str(value).strip()
    # Strip all non-numeric characters except decimal point
    cleaned = re.sub(r"[^0-9.]", "", value)

    if feature_name.lower() in ("region", "location", "area_name", "city", "state", "text", "description", "review"):
        # Ordinal hash encoding for categorical fields
        return str(sum(ord(ch) for ch in value.lower()) % 1000)

    try:
        return str(float(cleaned)) if cleaned else "0.0"
    except ValueError:
        return str(sum(ord(ch) for ch in value.lower()) % 1000)


def _is_numeric(value: str) -> bool:
    try:
        float(str(value).strip())
        return True
    except Exception:
        return False


def _local_fallback_prediction(values_list: List[str]) -> str:
    nums = [float(v) for v in values_list if _is_numeric(v)]
    if not nums:
        return "0.0"
    return str(round(sum(nums) / max(len(nums), 1), 3))


def _is_recoverable_endpoint_error(exc: Exception) -> bool:
    text = str(exc).lower()
    recoverable_tokens = (
        "could not connect to the endpoint url",
        "validationerror",
        "could not find endpoint",
        "endpoint",
        "not found",
        "does not exist",
    )
    return any(token in text for token in recoverable_tokens)


def validate_payload(payload: Dict[str, str]) -> Tuple[bool, str]:
    missing = [f for f in FEATURES if not str(payload.get(f, "")).strip()]
    if missing:
        return False, f"Missing required fields: {', '.join(missing)}"
    geo_fields = {"region", "location", "area_name", "city", "state"}
    for gf in geo_fields:
        if gf in FEATURES and not str(payload.get(gf, "")).strip():
            return False, f"'{gf}' is required for location-specific prediction."
    return True, ""


def make_prediction(values_list: List[str]) -> str:
    payload_str = ",".join(values_list)
    sm_runtime = get_sm_runtime()
    if sm_runtime is None or MOCK_MODE:
        return _local_fallback_prediction(values_list)
    try:
        response = sm_runtime.invoke_endpoint(
            EndpointName=ENDPOINT_NAME,
            ContentType="text/csv",
            Body=payload_str,
        )
        return response["Body"].read().decode("utf-8").strip()
    except Exception as exc:
        if _is_recoverable_endpoint_error(exc):
            return _local_fallback_prediction(values_list)
        raise RuntimeError(f"SageMaker endpoint error: {exc}") from exc


def predict_record(record: Dict[str, str]) -> str:
    encoded = [_encode_feature(f, record.get(f, "")) for f in FEATURES]
    return make_prediction(encoded)


# ── Sidebar — model info ──────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("""
    <div style="text-align:center;padding:0.5rem 0 1rem 0;">
      <div style="font-size:2.8rem;margin-bottom:0.3rem;">🔮</div>
      <div style="font-size:1.3rem;font-weight:800;color:#ffffff;letter-spacing:0.5px;">RAD-ML Predictor</div>
      <div style="font-size:0.8rem;color:#93c5fd;margin-top:2px;">AI-Powered Inference Engine</div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown('<hr style="border-color:rgba(59,130,246,0.35);margin:0.5rem 0 1rem 0;">', unsafe_allow_html=True)

    mode_color  = "#f59e0b" if MOCK_MODE else "#10b981"
    mode_label  = "Local Fallback" if MOCK_MODE else "SageMaker Live"
    mode_icon   = "💻" if MOCK_MODE else "☁️"

    st.markdown(f"""
    <div style="background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.12);
                border-radius:12px;padding:1rem;margin-bottom:1rem;">
      <div style="color:#94a3b8;font-size:0.75rem;font-weight:600;text-transform:uppercase;
                  letter-spacing:0.8px;margin-bottom:0.6rem;">INFERENCE MODE</div>
      <div style="display:flex;align-items:center;gap:8px;">
        <span style="font-size:1.2rem;">{mode_icon}</span>
        <span style="color:{mode_color};font-weight:700;font-size:0.95rem;">{mode_label}</span>
      </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown(f"""
    <div style="background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.12);
                border-radius:12px;padding:1rem;">
      <div style="color:#94a3b8;font-size:0.75rem;font-weight:600;text-transform:uppercase;
                  letter-spacing:0.8px;margin-bottom:0.8rem;">MODEL SETTINGS</div>
      <div style="display:flex;justify-content:space-between;margin-bottom:0.5rem;">
        <span style="color:#cbd5e1;font-size:0.88rem;">Algorithm</span>
        <span style="color:#60a5fa;font-weight:700;font-size:0.95rem;">XGBoost</span>
      </div>
      <div style="display:flex;justify-content:space-between;margin-bottom:0.5rem;">
        <span style="color:#cbd5e1;font-size:0.88rem;">Features</span>
        <span style="color:#a78bfa;font-weight:700;font-size:0.95rem;">{len(FEATURES)}</span>
      </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown('<hr style="border-color:rgba(59,130,246,0.35);margin:1rem 0;">', unsafe_allow_html=True)
    st.markdown("**Metrics (benchmark)**")
    c1, c2, c3 = st.columns(3)
    c1.metric("MAE", "—")
    c2.metric("RMSE", "—")
    c3.metric("R²", "—")
    st.caption("Metrics update after first prediction batch.")


# ── Main area ─────────────────────────────────────────────────────────────────
st.markdown("""
<div style="margin-bottom:1.5rem;">
  <h1 style="margin-bottom:0.2rem;">🔮 RAD-ML Predictor</h1>
  <p style="color:#93c5fd;font-size:1rem;margin:0;">Interactive ML inference via AWS SageMaker</p>
</div>
""", unsafe_allow_html=True)

tab_single, tab_bulk = st.tabs(["📊 Single Predict", "📁 Bulk Predict"])

# ── Tab 1: Single prediction ──────────────────────────────────────────────────
with tab_single:
    st.subheader("Enter Input Values")

    with st.form("single_predict_form"):
        cols = st.columns(2)
        inputs: Dict[str, str] = {}
        for idx, feat in enumerate(FEATURES):
            label = FEATURE_LABELS.get(feat, feat.replace("_", " ").title())
            with cols[idx % 2]:
                if "text" in feat.lower() or "review" in feat.lower() or "description" in feat.lower():
                    inputs[feat] = st.text_area(label, key=f"single_{feat}", placeholder=f"Enter {label}")
                else:
                    inputs[feat] = st.text_input(label, key=f"single_{feat}", placeholder=f"Enter {label}")

        st.markdown("<br/>", unsafe_allow_html=True)
        submitted = st.form_submit_button("🚀 Run Prediction", use_container_width=True, type="primary")

    if submitted:
        ok, error_msg = validate_payload(inputs)
        if not ok:
            st.error(f"⚠️ {error_msg}")
        else:
            try:
                with st.spinner("🤖 Running inference…"):
                    prediction = predict_record(inputs)
                st.markdown(
                    f'<div class="prediction-result">'
                    f'<p style="color:#94a3b8;font-size:0.95rem;font-weight:600;text-transform:uppercase;letter-spacing:1.5px;margin-bottom:10px;">Prediction Result</p>'
                    f'<h1 style="font-size:3.5rem;font-weight:800;margin:0;background:linear-gradient(135deg,#60a5fa,#c084fc);'
                    f'-webkit-background-clip:text;-webkit-text-fill-color:transparent">{prediction}</h1>'
                    f'</div>',
                    unsafe_allow_html=True,
                )
            except Exception as exc:
                st.error(f"Inference failed: {exc}")

# ── Tab 2: Bulk prediction ────────────────────────────────────────────────────
with tab_bulk:
    st.subheader("Bulk Predict from CSV")
    if pd is None:
        st.info("Install `pandas` to enable bulk prediction from CSV files.")
    else:
        uploaded_file = st.file_uploader(
            f"Upload a CSV with columns: {', '.join(FEATURES)}",
            type=["csv"],
        )
        if uploaded_file is not None:
            try:
                df = pd.read_csv(uploaded_file)
            except Exception as exc:
                st.error(f"Failed to parse CSV: {exc}")
                df = None

            if df is not None:
                missing_cols = [f for f in FEATURES if f not in df.columns]
                if missing_cols:
                    st.error(f"CSV is missing required columns: {', '.join(missing_cols)}")
                else:
                    st.dataframe(df.head(20), use_container_width=True)
                    st.markdown("<br/>", unsafe_allow_html=True)
                    if st.button("▶️ Run Bulk Prediction", type="primary"):
                        predictions = []
                        progress = st.progress(0, text="Running inference…")
                        try:
                            for i, (_, row) in enumerate(df.iterrows()):
                                rec = {f: str(row.get(f, "")) for f in FEATURES}
                                ok, error_msg = validate_payload(rec)
                                if not ok:
                                    predictions.append(f"ERROR: {error_msg}")
                                else:
                                    predictions.append(predict_record(rec))
                                progress.progress((i + 1) / len(df), text=f"Row {i+1}/{len(df)}")

                            out_df = df.copy()
                            out_df["prediction"] = predictions
                            st.success(f"✅ Completed {len(df)} predictions.")
                            st.dataframe(out_df, use_container_width=True)

                            csv_bytes = out_df.to_csv(index=False).encode("utf-8")
                            st.download_button(
                                "⬇️ Download Predictions CSV",
                                data=csv_bytes,
                                file_name="predictions.csv",
                                mime="text/csv",
                                use_container_width=True,
                            )
                        except Exception as exc:
                            st.error(f"Bulk inference failed: {exc}")


if __name__ == "__main__":
    pass  # Launched via: streamlit run app.py
'''


# ── Patch STREAMLIT_APP_ML in base_streamlit.py ──────────────────────────────
src = TARGET.read_text(encoding="utf-8")
start_marker = "# ---------------------------------------------------------------------------\nSTREAMLIT_APP_ML = "
end_marker = "# RECOMMENDATION"

start_idx = src.find(start_marker)
end_idx = src.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print("Could not find markers to patch base_streamlit.py")
else:
    # Need to find the exact line before # RECOMMENDATION
    before_rec = src[:end_idx].rstrip()
    last_triple_quote = before_rec.rfind("'''")
    if last_triple_quote != -1:
        before = src[:start_idx]
        after = src[last_triple_quote + 3:]

        new_section = "# ---------------------------------------------------------------------------\nSTREAMLIT_APP_ML = '''" + INNER + "'''\n\n\n"
        TARGET.write_text(before + new_section + after, encoding="utf-8")
        print("[OK] base_streamlit.py patched")

# ── Patch the local running app.py ──────────────────────────────────────────
if APP.exists():
    APP.write_text(INNER, encoding="utf-8")
    print(f"[OK] {APP} overwritten with high-contrast ML template.")
