"""
patch_recommendation_template.py
Replaces STREAMLIT_APP_RECOMMENDATION in base_streamlit.py with the new
movie-recommendation UI (genre dropdown + min-rating slider → movie cards).
Run from: Code_Generator/RAD-ML/
"""
import pathlib
import sys

TARGET = pathlib.Path(__file__).resolve().parent / "generator" / "base_streamlit.py"

# ── New recommendation template ───────────────────────────────────────────────
NEW_REC = (
    "\n"
    "\n"
    "# ---------------------------------------------------------------------------\n"
    "# RECOMMENDATION — Movie recommendation Streamlit App\n"
    "# ---------------------------------------------------------------------------\n"
    "STREAMLIT_APP_RECOMMENDATION = "
)

INNER = r'''"""
Movie Recommendation Streamlit app generated by RAD-ML.
Accepts genre (dropdown) and min-rating (slider) and returns a ranked list of movies.
"""
from __future__ import annotations
import os, re, sys
from pathlib import Path
from typing import Dict, List

import streamlit as st
import yaml

try:
    import boto3
except Exception:
    boto3 = None  # type: ignore

try:
    import pandas as pd
except Exception:
    pd = None  # type: ignore

ROOT = next(
    (p for p in Path(__file__).resolve().parents if (p / "config.yaml").exists()),
    Path(__file__).resolve().parent,
)
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)
os.environ.setdefault("AWS_EC2_METADATA_DISABLED", "true")

_cfg_path = ROOT / "config.yaml"
CFG: dict = {}
if _cfg_path.exists():
    try:
        with open(_cfg_path, encoding="utf-8") as _f:
            CFG = yaml.safe_load(_f) or {}
    except Exception:
        CFG = {}

st.set_page_config(page_title="Movie Recommender", page_icon="🎬", layout="wide",
                   initial_sidebar_state="expanded")

st.markdown("""
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
  html,body,[class*="css"]{font-family:'Inter',sans-serif;}
  [data-testid="stAppViewContainer"]{background:#0d0f1a;}
  [data-testid="stSidebar"]{background:#12152a;border-right:1px solid rgba(255,255,255,.07);}
  h1,h2,h3{color:#e8eaf0!important;}
  .stCaption{color:#8a8fa8!important;}
  .mcard{background:linear-gradient(135deg,rgba(62,207,255,.07),rgba(124,106,247,.07));
         border:1px solid rgba(62,207,255,.18);border-radius:14px;
         padding:1rem 1.4rem;margin-bottom:.8rem;}
  .mcard:hover{border-color:rgba(62,207,255,.45);}
  .mrank{font-size:1.1rem;font-weight:700;color:#3ecfff;}
  .mtitle{font-size:1.05rem;font-weight:600;color:#e8eaf0;}
  .mmeta{font-size:.82rem;color:#8a8fa8;margin-top:.2rem;}
  .star{color:#f5c518;}
  .gbadge{display:inline-block;padding:2px 8px;border-radius:6px;font-size:.75rem;
          font-weight:600;background:rgba(124,106,247,.25);color:#c4b5fd;margin-right:4px;}
  .noresult{background:rgba(255,100,100,.07);border:1px solid rgba(255,100,100,.2);
            border-radius:12px;padding:2rem;text-align:center;color:#e8eaf0;}
</style>""", unsafe_allow_html=True)

ENDPOINT_NAME   = os.environ.get("SAGEMAKER_ENDPOINT", "rad-ml-endpoint")
AWS_REGION      = CFG.get("aws", {}).get("region", "us-east-1")
REMOTE_ENABLED  = os.environ.get("SAGEMAKER_REMOTE_ENABLED", "1") == "1"
MOCK_MODE       = not REMOTE_ENABLED or os.environ.get("RADML_MOCK_MODE", "0") == "1"

CATALOGUE: List[Dict] = [
    {"title":"The Dark Knight",         "genre":"Action",    "rating":9.0,"year":2008,"desc":"Batman faces the Joker's reign of terror."},
    {"title":"Inception",               "genre":"Sci-Fi",    "rating":8.8,"year":2010,"desc":"A thief who enters people's dreams."},
    {"title":"Interstellar",            "genre":"Sci-Fi",    "rating":8.6,"year":2014,"desc":"Explorers travel through a wormhole in space."},
    {"title":"The Avengers",            "genre":"Action",    "rating":8.0,"year":2012,"desc":"Earth's mightiest heroes unite."},
    {"title":"John Wick",               "genre":"Action",    "rating":7.4,"year":2014,"desc":"A retired hitman seeks vengeance."},
    {"title":"The Matrix",              "genre":"Sci-Fi",    "rating":8.7,"year":1999,"desc":"A hacker discovers reality is a simulation."},
    {"title":"Mad Max: Fury Road",      "genre":"Action",    "rating":8.1,"year":2015,"desc":"Post-apocalyptic high-speed chase."},
    {"title":"Gravity",                 "genre":"Sci-Fi",    "rating":7.7,"year":2013,"desc":"Two astronauts stranded in outer space."},
    {"title":"Top Gun: Maverick",       "genre":"Action",    "rating":8.3,"year":2022,"desc":"Naval aviator returns for a dangerous mission."},
    {"title":"Avatar",                  "genre":"Sci-Fi",    "rating":7.9,"year":2009,"desc":"A paralysed marine on the planet Pandora."},
    {"title":"The Shawshank Redemption","genre":"Drama",     "rating":9.3,"year":1994,"desc":"Two imprisoned men bond over years."},
    {"title":"Forrest Gump",            "genre":"Drama",     "rating":8.8,"year":1994,"desc":"Life of a man with a low IQ but good heart."},
    {"title":"Schindler's List",        "genre":"Drama",     "rating":9.0,"year":1993,"desc":"A businessman saves Jewish lives in WWII."},
    {"title":"The Pursuit of Happyness","genre":"Drama",     "rating":8.0,"year":2006,"desc":"A struggling salesman fights for his son."},
    {"title":"Good Will Hunting",       "genre":"Drama",     "rating":8.3,"year":1997,"desc":"A janitor is secretly a math genius."},
    {"title":"Whiplash",                "genre":"Drama",     "rating":8.5,"year":2014,"desc":"A jazz student pushed to his limits."},
    {"title":"12 Angry Men",            "genre":"Drama",     "rating":8.9,"year":1957,"desc":"Jury deliberation for a murder case."},
    {"title":"The Hangover",            "genre":"Comedy",    "rating":7.7,"year":2009,"desc":"Three friends wake up with no memory of a bachelor party."},
    {"title":"Groundhog Day",           "genre":"Comedy",    "rating":8.0,"year":1993,"desc":"A man relives the same day over and over."},
    {"title":"The Grand Budapest Hotel","genre":"Comedy",    "rating":8.1,"year":2014,"desc":"Adventures of a legendary hotel concierge."},
    {"title":"Home Alone",              "genre":"Comedy",    "rating":7.7,"year":1990,"desc":"A boy is accidentally left home alone."},
    {"title":"Superbad",                "genre":"Comedy",    "rating":7.6,"year":2007,"desc":"Two co-dependent high-schoolers on a wild night."},
    {"title":"The Conjuring",           "genre":"Horror",    "rating":7.5,"year":2013,"desc":"Paranormal investigators fight a dark presence."},
    {"title":"Get Out",                 "genre":"Horror",    "rating":7.7,"year":2017,"desc":"A man uncovers a disturbing secret."},
    {"title":"A Quiet Place",           "genre":"Horror",    "rating":7.5,"year":2018,"desc":"A family survives in silence to avoid creatures."},
    {"title":"Hereditary",              "genre":"Horror",    "rating":7.3,"year":2018,"desc":"A family haunted after a grandmother's death."},
    {"title":"The Silence of the Lambs","genre":"Thriller",  "rating":8.6,"year":1991,"desc":"FBI trainee seeks a cannibalistic killer's help."},
    {"title":"Se7en",                   "genre":"Thriller",  "rating":8.6,"year":1995,"desc":"Two detectives hunt a serial killer."},
    {"title":"Gone Girl",               "genre":"Thriller",  "rating":8.1,"year":2014,"desc":"A woman disappears on her anniversary."},
    {"title":"Parasite",                "genre":"Thriller",  "rating":8.5,"year":2019,"desc":"A poor family infiltrates a wealthy household."},
    {"title":"The Notebook",            "genre":"Romance",   "rating":7.8,"year":2004,"desc":"Two young lovers from different worlds."},
    {"title":"Pride & Prejudice",       "genre":"Romance",   "rating":7.8,"year":2005,"desc":"Romance between Elizabeth Bennet and Mr Darcy."},
    {"title":"La La Land",              "genre":"Romance",   "rating":8.0,"year":2016,"desc":"A musician and actress fall in love in LA."},
    {"title":"Titanic",                 "genre":"Romance",   "rating":7.9,"year":1997,"desc":"A love story aboard the ill-fated ship."},
    {"title":"The Lord of the Rings",   "genre":"Fantasy",   "rating":8.9,"year":2001,"desc":"A hobbit carries a powerful ring on an epic quest."},
    {"title":"Harry Potter",            "genre":"Fantasy",   "rating":7.6,"year":2001,"desc":"A young wizard embarks on magical adventures."},
    {"title":"Gladiator",               "genre":"Fantasy",   "rating":8.5,"year":2000,"desc":"A Roman general becomes a slave gladiator."},
    {"title":"Coco",                    "genre":"Animation", "rating":8.4,"year":2017,"desc":"A boy travels to the Land of the Dead."},
    {"title":"Spirited Away",           "genre":"Animation", "rating":8.6,"year":2001,"desc":"A girl moves to a spirit world."},
    {"title":"The Lion King",           "genre":"Animation", "rating":8.5,"year":1994,"desc":"A lion cub's journey to become king."},
    {"title":"Up",                      "genre":"Animation", "rating":8.2,"year":2009,"desc":"An elderly man flies his house using balloons."},
    {"title":"Goodfellas",              "genre":"Crime",     "rating":8.7,"year":1990,"desc":"Rise and fall of a mob associate."},
    {"title":"The Godfather",           "genre":"Crime",     "rating":9.2,"year":1972,"desc":"The powerful Corleone crime family."},
    {"title":"Heat",                    "genre":"Crime",     "rating":8.2,"year":1995,"desc":"A detective tracks a brilliant thief."},
    {"title":"City of God",             "genre":"Crime",     "rating":8.6,"year":2002,"desc":"Youth gangs in Rio de Janeiro."},
]

ALL_GENRES = sorted({m["genre"] for m in CATALOGUE})


def _local_recommend(genre: str, min_rating: float, top_n: int) -> List[Dict]:
    gl = genre.lower()
    filtered = [m for m in CATALOGUE if (gl == "all" or m["genre"].lower() == gl) and m["rating"] >= min_rating]
    ranked = sorted(filtered, key=lambda m: m["rating"], reverse=True)[:top_n]
    return [{"rank": i + 1, **m} for i, m in enumerate(ranked)]


def get_recommendations(genre: str, min_rating: float, top_n: int) -> List[Dict]:
    if not boto3 or MOCK_MODE:
        return _local_recommend(genre, min_rating, top_n)
    try:
        sm = boto3.client("sagemaker-runtime", region_name=AWS_REGION)
        payload = f"{sum(ord(c) for c in genre.lower()) % 1000},{min_rating}"
        raw = sm.invoke_endpoint(EndpointName=ENDPOINT_NAME, ContentType="text/csv", Body=payload)
        titles = [t.strip() for t in raw["Body"].read().decode().split(",") if t.strip()]
        if titles:
            return [{"rank": i+1, "title": t, "genre": genre, "rating": "—", "year": "—", "desc": ""}
                    for i, t in enumerate(titles[:top_n])]
    except Exception:
        pass
    return _local_recommend(genre, min_rating, top_n)


def _stars(r) -> str:
    try:
        v = float(r); full = int(v / 2)
        return "★" * full + "☆" * (5 - full) + f"  {v:.1f}/10"
    except Exception:
        return str(r)


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🎬 Movie Recommender")
    st.caption("Powered by RAD-ML + curated catalogue")
    st.divider()
    top_n = st.slider("Number of movies", 3, 20, 10)
    st.divider()
    st.caption(f"**Mode:** {'🟡 Local catalogue' if MOCK_MODE else '🟢 SageMaker'}")
    st.caption(f"**Catalogue:** {len(CATALOGUE)} movies | {len(ALL_GENRES)} genres")

# ── Main ──────────────────────────────────────────────────────────────────────
st.title("🎬 Movie Recommendation Engine")
st.caption("Choose a genre and minimum rating — we'll find the best movies for you.")

with st.form("rec_form"):
    c1, c2, c3 = st.columns([2, 2, 1], gap="medium")
    with c1:
        genre_sel = st.selectbox("🎭 Genre", ["All"] + ALL_GENRES, index=0,
                                 help="Pick the genre you enjoy most.")
    with c2:
        min_rat = st.slider("⭐ Minimum Rating", 0.0, 10.0, 7.0, 0.5,
                            help="Show only movies rated ≥ this value out of 10.")
    with c3:
        st.markdown("<br/>", unsafe_allow_html=True)
        go = st.form_submit_button("🎬 Recommend", use_container_width=True, type="primary")

st.divider()

if go:
    with st.spinner("Fetching recommendations…"):
        recs = get_recommendations(genre_sel, min_rat, top_n)

    if not recs:
        st.markdown(
            f'<div class="noresult"><h3>😕 No matches found</h3>'
            f'<p>No <strong>{genre_sel}</strong> movies with rating ≥ {min_rat}.<br>'
            f'Try lowering the minimum rating or selecting a different genre.</p></div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            f"### 🏆 Top {len(recs)} Results"
            f'<span style="color:#8a8fa8;font-size:.9rem;margin-left:.8rem;">'
            f'Genre: <strong style="color:#c4b5fd">{genre_sel}</strong> &nbsp;|&nbsp; '
            f'Min Rating: <strong style="color:#f5c518">{min_rat}</strong></span>',
            unsafe_allow_html=True,
        )
        cols = st.columns(2)
        for i, m in enumerate(recs):
            with cols[i % 2]:
                st.markdown(
                    f'<div class="mcard">'
                    f'<span class="mrank">#{m["rank"]}</span>&nbsp;&nbsp;'
                    f'<span class="mtitle">{m["title"]}</span>'
                    f'<div class="mmeta"><span class="gbadge">{m["genre"]}</span>'
                    f'&nbsp;{m.get("year","")} &nbsp;|&nbsp;'
                    f'<span class="star">{_stars(m["rating"])}</span></div>'
                    f'<div class="mmeta" style="margin-top:.35rem;color:#b0b5cc;">{m.get("desc","")}</div>'
                    f'</div>',
                    unsafe_allow_html=True,
                )
        if pd is not None:
            edf = pd.DataFrame(recs)[["rank","title","genre","rating","year"]]
            st.download_button("⬇️ Download CSV", edf.to_csv(index=False).encode(),
                               "movie_recs.csv", "text/csv")
else:
    st.markdown(
        '<div style="text-align:center;padding:3rem;color:#8a8fa8;">'
        '<div style="font-size:3rem">🎬</div>'
        '<h3 style="color:#8a8fa8;">Select a genre and rating above, then click Recommend</h3>'
        '</div>', unsafe_allow_html=True,
    )

if __name__ == "__main__":
    pass
'''

# ── Patch the file ────────────────────────────────────────────────────────────
src = TARGET.read_text(encoding="utf-8")

# Find where STREAMLIT_APP_RECOMMENDATION starts
rec_start_marker = "# ---------------------------------------------------------------------------\n# RECOMMENDATION"
idx = src.find(rec_start_marker)
if idx == -1:
    print("ERROR: could not find RECOMMENDATION section marker in base_streamlit.py")
    sys.exit(1)

# Keep everything before it, replace the rest with our new template
before = src[:idx]
new_section = (
    "# ---------------------------------------------------------------------------\n"
    "# RECOMMENDATION — Movie recommendation Streamlit App\n"
    "# ---------------------------------------------------------------------------\n"
    "STREAMLIT_APP_RECOMMENDATION = '''" + INNER + "'''\n"
)
new_src = before + new_section
TARGET.write_text(new_src, encoding="utf-8")
print(f"[OK] base_streamlit.py updated — STREAMLIT_APP_RECOMMENDATION replaced ({len(new_src)} chars)")
