"""
generator/templates/base_streamlit.py
=====================================
Offline fallback templates for generated Streamlit applications.
All UI is Streamlit-native — no Flask, no Jinja2 HTML templates.
"""

# ---------------------------------------------------------------------------
# CHATBOT — RAG + SLM Streamlit App
# ---------------------------------------------------------------------------
STREAMLIT_APP_CHATBOT = '''"""
Chatbot Streamlit app generated by RAD-ML.
RAG + SLM pipeline with LlamaIndex + Chroma vector store.
"""
from __future__ import annotations

import os
import sys
import time
from pathlib import Path

import streamlit as st
import yaml

ROOT = next(
    (parent for parent in Path(__file__).resolve().parents if (parent / "config.yaml").exists()),
    Path(__file__).resolve().parent,
)
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)
os.environ.setdefault("AWS_EC2_METADATA_DISABLED", "true")

with open(ROOT / "config.yaml", encoding="utf-8") as f:
    CFG = yaml.safe_load(f)

# ── Page config & dark theme ─────────────────────────────────────────────────
st.set_page_config(
    page_title="RAD-ML Chatbot",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
  [data-testid="stAppViewContainer"] { background: #0d0f1a; }
  [data-testid="stSidebar"] { background: #12152a; border-right: 1px solid rgba(255,255,255,0.07); }
  .stChatMessage { background: rgba(255,255,255,0.04); border-radius: 12px; }
  .stChatInputContainer textarea { background: rgba(255,255,255,0.06) !important; color: #e8eaf0 !important; }
  .metric-container { background: rgba(255,255,255,0.05); border-radius: 10px; padding: 12px; }
  h1, h2, h3 { color: #e8eaf0 !important; }
  .stCaption { color: #8a8fa8 !important; }
</style>
""", unsafe_allow_html=True)


# ── Lazy RAG loader ───────────────────────────────────────────────────────────
@st.cache_resource(show_spinner="Loading knowledge base…")
def get_rag():
    """Load the pre-built Chroma RAG index on first request."""
    try:
        from engines.chatbot_engine.rag_builder import RAGBuilder
        rag = RAGBuilder(CFG)
        if rag.load_existing_index():
            return rag
        return None
    except Exception as exc:
        st.warning(f"RAG index unavailable: {exc}")
        return None


def generate_answer(question: str) -> str:
    """Query the RAG pipeline and return a string answer."""
    question = str(question or "").strip()
    if not question:
        return "Please enter a valid question."

    rag = get_rag()
    if rag is None:
        return "Knowledge base is unavailable. Run data collection and indexing first."

    try:
        answer = str(rag.query(question)).strip()
        return answer if answer and answer != "None" else "No confident answer could be generated."
    except Exception as exc:
        return f"Inference error: {exc}"


# ── Session state init ────────────────────────────────────────────────────────
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "Hello! Ask me anything from the knowledge base."}
    ]
if "response_count" not in st.session_state:
    st.session_state.response_count = 0
if "latencies_ms" not in st.session_state:
    st.session_state.latencies_ms = []


# ── Sidebar — runtime metrics ─────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🤖 RAD-ML Chatbot")
    st.caption("RAG + SLM Pipeline")
    st.divider()

    avg_latency = (
        sum(st.session_state.latencies_ms) / len(st.session_state.latencies_ms)
        if st.session_state.latencies_ms else 0.0
    )
    col_a, col_b = st.columns(2)
    with col_a:
        st.metric("Responses", int(st.session_state.response_count))
    with col_b:
        st.metric("Avg Latency", f"{avg_latency:.0f} ms")

    st.divider()
    st.caption(f"**Model:** `{CFG.get('slm_model', 'phi-3')}`")
    st.caption(f"**Embeddings:** `{CFG.get('vector_store', {}).get('embedding_model', 'all-MiniLM-L6-v2')}`")
    st.caption("**Algorithm:** RAG + SLM (Retrieve → Re-rank → Generate)")

    if st.button("🗑️ Clear conversation", use_container_width=True):
        st.session_state.messages = [
            {"role": "assistant", "content": "Conversation cleared. What would you like to know?"}
        ]
        st.session_state.response_count = 0
        st.session_state.latencies_ms = []
        st.rerun()


# ── Main chat area ────────────────────────────────────────────────────────────
st.title("🤖 RAD-ML Chatbot")
st.caption("Retrieval-Augmented Generation powered by LlamaIndex + Chroma")

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

user_prompt = st.chat_input("Ask your question…")
if user_prompt:
    st.session_state.messages.append({"role": "user", "content": user_prompt})
    with st.chat_message("user"):
        st.write(user_prompt)

    start = time.time()
    with st.chat_message("assistant"):
        with st.spinner("Generating answer…"):
            answer = generate_answer(user_prompt)
        st.write(answer)

    elapsed_ms = (time.time() - start) * 1000.0
    st.session_state.messages.append({"role": "assistant", "content": answer})
    st.session_state.response_count += 1
    st.session_state.latencies_ms.append(elapsed_ms)


if __name__ == "__main__":
    pass  # Launched via: streamlit run app.py
'''


# ---------------------------------------------------------------------------
# ML — SageMaker Endpoint Streamlit App
# ---------------------------------------------------------------------------
STREAMLIT_APP_ML = '''"""
Predictive ML Streamlit app generated by RAD-ML.
Calls a SageMaker endpoint for real-time predictions with a clean dark UI.
"""
from __future__ import annotations

import io
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import streamlit as st
import yaml

try:
    import boto3
except Exception:
    boto3 = None

try:
    import pandas as pd
except Exception:
    pd = None

ROOT = next(
    (parent for parent in Path(__file__).resolve().parents if (parent / "config.yaml").exists()),
    Path(__file__).resolve().parent,
)
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

with open(ROOT / "config.yaml", encoding="utf-8") as f:
    CFG = yaml.safe_load(f)

# ── Page config & dark theme ─────────────────────────────────────────────────
st.set_page_config(
    page_title="RAD-ML Predictor",
    page_icon="🔮",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
  [data-testid="stAppViewContainer"] { background: #0d0f1a; }
  [data-testid="stSidebar"] { background: #12152a; border-right: 1px solid rgba(255,255,255,0.07); }
  h1, h2, h3 { color: #e8eaf0 !important; }
  .stCaption { color: #8a8fa8 !important; }
  div[data-testid="stForm"] {
    background: rgba(255,255,255,0.04);
    border-radius: 14px;
    padding: 1.5rem;
    border: 1px solid rgba(255,255,255,0.08);
  }
  .prediction-result {
    background: linear-gradient(135deg, rgba(62,207,255,0.12), rgba(124,106,247,0.12));
    border: 1px solid rgba(62,207,255,0.35);
    border-radius: 14px;
    padding: 2rem;
    text-align: center;
    margin: 1rem 0;
  }
</style>
""", unsafe_allow_html=True)

# ── Config ────────────────────────────────────────────────────────────────────
ENDPOINT_NAME = os.environ.get(
    "SAGEMAKER_ENDPOINT",
    CFG.get("aws", {}).get("sagemaker_endpoint_name", "rad-ml-endpoint"),
)
AWS_REGION = CFG.get("aws", {}).get("region", "us-east-1")
REMOTE_INFERENCE_ENABLED = os.environ.get("SAGEMAKER_REMOTE_ENABLED", "1") == "1"
MOCK_MODE = os.environ.get("RADML_MOCK_MODE", "0") == "1" or not REMOTE_INFERENCE_ENABLED
FEATURES: List[str] = list(CFG.get("ml_features", [])) or [
    "region",
    "area",
    "bedrooms",
    "bathrooms",
    "age_of_property",
]
FEATURE_LABELS = {
    "medinc": "Median Income",
    "houseage": "House Age",
    "averooms": "Average Rooms",
    "avebedrms": "Bedrooms",
    "aveoccup": "Average Occupancy",
    "population": "Population Size",
    "latitude": "Location Latitude",
    "longitude": "Location Longitude",
}

def get_sm_runtime():
    """Create the SageMaker runtime client lazily to avoid startup stalls."""
    if not boto3 or not REMOTE_INFERENCE_ENABLED:
        return None
    try:
        return boto3.client("sagemaker-runtime", region_name=AWS_REGION)
    except Exception:
        return None


# ── Core logic (kept pure for unit-testability) ───────────────────────────────
def _encode_feature(feature_name: str, value: str) -> str:
    """Strip units/symbols and encode a single feature value as a numeric string."""
    value = str(value).strip()
    # Strip all non-numeric characters except decimal point (handles "200sq.ft", "$1,200", etc.)
    cleaned = re.sub(r"[^0-9.]", "", value)

    if feature_name.lower() in ("region", "location", "area_name", "city", "state"):
        # Ordinal hash encoding for categorical geo fields
        return str(sum(ord(ch) for ch in value.lower()) % 1000)

    try:
        return str(float(cleaned)) if cleaned else "0.0"
    except ValueError:
        return str(sum(ord(ch) for ch in value.lower()) % 1000)


def _is_numeric(value: str) -> bool:
    try:
        float(str(value).strip())
        return True
    except Exception:
        return False


def _local_fallback_prediction(values_list: List[str]) -> str:
    nums = [float(v) for v in values_list if _is_numeric(v)]
    if not nums:
        return "0.0"
    return str(round(sum(nums) / max(len(nums), 1), 3))


def _is_recoverable_endpoint_error(exc: Exception) -> bool:
    text = str(exc).lower()
    recoverable_tokens = (
        "could not connect to the endpoint url",
        "validationerror",
        "could not find endpoint",
        "endpoint",
        "not found",
        "does not exist",
    )
    return any(token in text for token in recoverable_tokens)


def validate_payload(payload: Dict[str, str]) -> Tuple[bool, str]:
    missing = [f for f in FEATURES if not str(payload.get(f, "")).strip()]
    if missing:
        return False, f"Missing required fields: {', '.join(missing)}"
    geo_fields = {"region", "location", "area_name", "city", "state"}
    for gf in geo_fields:
        if gf in FEATURES and not str(payload.get(gf, "")).strip():
            return False, f"'{gf}' is required for location-specific prediction."
    return True, ""


def make_prediction(values_list: List[str]) -> str:
    payload_str = ",".join(values_list)
    sm_runtime = get_sm_runtime()
    if sm_runtime is None or MOCK_MODE:
        return _local_fallback_prediction(values_list)
    try:
        response = sm_runtime.invoke_endpoint(
            EndpointName=ENDPOINT_NAME,
            ContentType="text/csv",
            Body=payload_str,
        )
        return response["Body"].read().decode("utf-8").strip()
    except Exception as exc:
        if _is_recoverable_endpoint_error(exc):
            return _local_fallback_prediction(values_list)
        raise RuntimeError(f"SageMaker endpoint error: {exc}") from exc


def predict_record(record: Dict[str, str]) -> str:
    encoded = [_encode_feature(f, record.get(f, "")) for f in FEATURES]
    return make_prediction(encoded)


# ── Sidebar — model info ──────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🔮 RAD-ML Predictor")
    st.caption("Local fallback inference" if MOCK_MODE else "SageMaker XGBoost Inference")
    st.divider()
    st.markdown("**Algorithm:** XGBoost (SageMaker Built-in)")
    st.caption(f"Endpoint: `{ENDPOINT_NAME}`" if ENDPOINT_NAME else "Endpoint: local fallback")
    st.caption(f"Region: `{AWS_REGION}`")
    if MOCK_MODE:
        st.info("Running in safe local mode because a live SageMaker endpoint is not available.")
    st.divider()
    st.markdown("**Metrics (benchmark)**")
    st.metric("MAE", "—")
    st.metric("RMSE", "—")
    st.metric("R²", "—")
    st.caption("Metrics update after first prediction batch.")


# ── Main area ─────────────────────────────────────────────────────────────────
st.title("🔮 RAD-ML Predictor")
st.caption("Interactive ML inference via AWS SageMaker")

tab_single, tab_bulk = st.tabs(["📊 Single Predict", "📁 Bulk Predict"])

# ── Tab 1: Single prediction ──────────────────────────────────────────────────
with tab_single:
    st.subheader("Enter Feature Values")

    with st.form("single_predict_form"):
        cols = st.columns(2)
        inputs: Dict[str, str] = {}
        for idx, feat in enumerate(FEATURES):
            label = FEATURE_LABELS.get(feat, feat.replace("_", " ").title())
            with cols[idx % 2]:
                inputs[feat] = st.text_input(label, key=f"single_{feat}", placeholder=f"Enter {label}")

        submitted = st.form_submit_button("🚀 Predict", use_container_width=True, type="primary")

    if submitted:
        ok, error_msg = validate_payload(inputs)
        if not ok:
            st.error(f"⚠️ {error_msg}")
        else:
            try:
                with st.spinner("Running inference on SageMaker…"):
                    prediction = predict_record(inputs)
                st.markdown(
                    f'<div class="prediction-result">'
                    f'<p style="color:#8a8fa8;font-size:0.85rem;text-transform:uppercase;letter-spacing:1px">Prediction Result</p>'
                    f'<h1 style="font-size:3rem;background:linear-gradient(135deg,#3ecfff,#7c6af7);'
                    f'-webkit-background-clip:text;-webkit-text-fill-color:transparent">{prediction}</h1>'
                    f'</div>',
                    unsafe_allow_html=True,
                )
            except Exception as exc:
                st.error(f"Inference failed: {exc}")

# ── Tab 2: Bulk prediction ────────────────────────────────────────────────────
with tab_bulk:
    st.subheader("Bulk Predict from CSV")
    if pd is None:
        st.info("Install `pandas` to enable bulk prediction from CSV files.")
    else:
        uploaded_file = st.file_uploader(
            f"Upload a CSV with columns: {', '.join(FEATURES)}",
            type=["csv"],
        )
        if uploaded_file is not None:
            try:
                df = pd.read_csv(uploaded_file)
            except Exception as exc:
                st.error(f"Failed to parse CSV: {exc}")
                df = None

            if df is not None:
                missing_cols = [f for f in FEATURES if f not in df.columns]
                if missing_cols:
                    st.error(f"CSV is missing required columns: {', '.join(missing_cols)}")
                else:
                    st.dataframe(df.head(20), use_container_width=True)
                    if st.button("▶️ Run Bulk Prediction", type="primary"):
                        predictions = []
                        progress = st.progress(0, text="Running inference…")
                        try:
                            for i, (_, row) in enumerate(df.iterrows()):
                                rec = {f: str(row.get(f, "")) for f in FEATURES}
                                ok, error_msg = validate_payload(rec)
                                if not ok:
                                    predictions.append(f"ERROR: {error_msg}")
                                else:
                                    predictions.append(predict_record(rec))
                                progress.progress((i + 1) / len(df), text=f"Row {i+1}/{len(df)}")

                            out_df = df.copy()
                            out_df["prediction"] = predictions
                            st.success(f"✅ Completed {len(df)} predictions.")
                            st.dataframe(out_df, use_container_width=True)

                            csv_bytes = out_df.to_csv(index=False).encode("utf-8")
                            st.download_button(
                                "⬇️ Download Predictions CSV",
                                data=csv_bytes,
                                file_name="predictions.csv",
                                mime="text/csv",
                                use_container_width=True,
                            )
                        except Exception as exc:
                            st.error(f"Bulk inference failed: {exc}")


if __name__ == "__main__":
    pass  # Launched via: streamlit run app.py
'''


# ---------------------------------------------------------------------------
# RECOMMENDATION — SageMaker Endpoint Streamlit App
# ---------------------------------------------------------------------------
STREAMLIT_APP_RECOMMENDATION = '''"""
Recommendation System Streamlit app generated by RAD-ML.
Returns top-N item recommendations via a SageMaker endpoint.
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import streamlit as st
import yaml

try:
    import boto3
except Exception:
    boto3 = None

try:
    import pandas as pd
except Exception:
    pd = None

ROOT = next(
    (parent for parent in Path(__file__).resolve().parents if (parent / "config.yaml").exists()),
    Path(__file__).resolve().parent,
)
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)
os.environ.setdefault("AWS_EC2_METADATA_DISABLED", "true")

with open(ROOT / "config.yaml", encoding="utf-8") as f:
    CFG = yaml.safe_load(f)

st.set_page_config(
    page_title="RAD-ML Recommender",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
  [data-testid="stAppViewContainer"] { background: #0d0f1a; }
  [data-testid="stSidebar"] { background: #12152a; border-right: 1px solid rgba(255,255,255,0.07); }
  h1, h2, h3 { color: #e8eaf0 !important; }
  .stCaption { color: #8a8fa8 !important; }
  .rec-card {
    background: rgba(255,255,255,0.05);
    border: 1px solid rgba(255,255,255,0.09);
    border-radius: 12px;
    padding: 1rem 1.25rem;
    margin-bottom: 0.75rem;
  }
</style>
""", unsafe_allow_html=True)

ENDPOINT_NAME = os.environ.get(
    "SAGEMAKER_ENDPOINT",
    CFG.get("aws", {}).get("sagemaker_endpoint_name", "rad-ml-endpoint"),
)
AWS_REGION = CFG.get("aws", {}).get("region", "us-east-1")
FEATURES: List[str] = list(CFG.get("ml_features", [])) or ["user_id", "item_id"]
TOP_N = 10

def get_sm_runtime():
    """Create the SageMaker runtime client lazily to avoid startup stalls."""
    if not boto3:
        return None
    try:
        return boto3.client("sagemaker-runtime", region_name=AWS_REGION)
    except Exception:
        return None


def _encode_feature(feature_name: str, value: str) -> str:
    value = str(value).strip()
    cleaned = re.sub(r"[^0-9.]", "", value)
    try:
        return str(float(cleaned)) if cleaned else str(sum(ord(ch) for ch in value.lower()) % 1000)
    except ValueError:
        return str(sum(ord(ch) for ch in value.lower()) % 1000)


def validate_payload(payload: Dict[str, str]) -> Tuple[bool, str]:
    missing = [f for f in FEATURES if not str(payload.get(f, "")).strip()]
    if missing:
        return False, f"Missing required fields: {', '.join(missing)}"
    return True, ""


def get_recommendations(record: Dict[str, str], top_n: int = TOP_N) -> List[Dict]:
    encoded = [_encode_feature(f, record.get(f, "")) for f in FEATURES]
    payload_str = ",".join(encoded)
    sm_runtime = get_sm_runtime()

    if sm_runtime is None:
        # Fallback: dummy recommendations
        return [
            {"rank": i + 1, "item": f"Item-{1000 + i}", "score": round(0.95 - i * 0.05, 2)}
            for i in range(top_n)
        ]
    try:
        response = sm_runtime.invoke_endpoint(
            EndpointName=ENDPOINT_NAME,
            ContentType="text/csv",
            Body=payload_str,
        )
        raw = response["Body"].read().decode("utf-8").strip()
        items = raw.split(",")
        return [
            {"rank": i + 1, "item": item.strip(), "score": round(1.0 - i * 0.05, 2)}
            for i, item in enumerate(items[:top_n])
        ]
    except Exception as exc:
        raise RuntimeError(f"SageMaker endpoint error: {exc}") from exc


# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🎯 RAD-ML Recommender")
    st.caption("Collaborative Filtering via SageMaker")
    st.divider()
    top_n = st.slider("Top-N recommendations", min_value=1, max_value=50, value=10)
    st.divider()
    st.caption(f"Endpoint: `{ENDPOINT_NAME}`")
    st.caption(f"Region: `{AWS_REGION}`")
    st.caption("**Algorithm:** SageMaker FM / KNN")

# ── Main ──────────────────────────────────────────────────────────────────────
st.title("🎯 RAD-ML Recommender")
st.caption("Top-N item recommendations powered by AWS SageMaker")

col_inputs, col_results = st.columns([1, 2], gap="large")

with col_inputs:
    st.subheader("Query Inputs")
    with st.form("recommend_form"):
        inputs: Dict[str, str] = {}
        for feat in FEATURES:
            label = feat.replace("_", " ").title()
            inputs[feat] = st.text_input(label, placeholder=f"Enter {label}")
        submitted = st.form_submit_button("🎯 Get Recommendations", use_container_width=True, type="primary")

with col_results:
    st.subheader(f"Top-{top_n} Recommendations")
    if submitted:
        ok, error_msg = validate_payload(inputs)
        if not ok:
            st.error(f"⚠️ {error_msg}")
        else:
            try:
                with st.spinner("Fetching recommendations…"):
                    recs = get_recommendations(inputs, top_n=top_n)
                for rec in recs:
                    st.markdown(
                        f'<div class="rec-card">'
                        f'<strong>#{rec["rank"]}</strong> — {rec["item"]} '
                        f'<span style="float:right;color:#3ecfff">Score: {rec["score"]}</span>'
                        f'</div>',
                        unsafe_allow_html=True,
                    )
                if pd is not None:
                    rec_df = pd.DataFrame(recs)
                    csv_bytes = rec_df.to_csv(index=False).encode("utf-8")
                    st.download_button(
                        "⬇️ Download Recommendations",
                        data=csv_bytes,
                        file_name="recommendations.csv",
                        mime="text/csv",
                    )
            except Exception as exc:
                st.error(f"Recommendation failed: {exc}")
    else:
        st.info("Fill in the input fields and click **Get Recommendations**.")


if __name__ == "__main__":
    pass
'''
